from dataclasses import dataclass
from datetime import datetime
from typing import Optional, Type


@dataclass
class TrackField:
    friendly: Optional[str] = None  # Human-readable name
    short: Optional[str] = None  # shorter human readable name
    type: Type = str  # Python type with default value
    editable: bool = True  # Can the user edit this field?
    placeholder: Optional[str] = None  # Placeholder text for UI
    longtext: bool = False  # useTextEdit if true, QlineEdit if false
    min: Optional[float] = None  # Minimum value (for numbers)
    max: Optional[float] = None  # Maximum value (for numbers)
    length: Optional[int] = None  # Maximum length (for strings)
    category: Optional[str] = (
        None  # Grouping or section name (Basic, Properties, Alias (different track name types), Date, Classical, Identification, User, Lyrics, Advanced)
    )
    tooltip: Optional[str] = None  # UI popup hint
    multiple: bool = False  # can be edited on multiple tracks at once


TRACK_FIELDS = {
    "track_name": TrackField(
        friendly="Track Name",
        short="Name",
        placeholder="Enter song title",
        category="Basic",
        tooltip="The credited name of the track in your preferred style",
    ),
    "track_id": TrackField(
        friendly="Track ID",
        short="ID",
        type=int,
        editable=False,
        category="Basic",
        tooltip="The Unique ID assigned to the track in the database.",
    ),
    "track_number": TrackField(
        friendly="Track Number",
        short="Track #",
        type=int,
        category="Basic",
        tooltip="The position of the track within its disc or side, following the original release ordering.",
    ),
    "absolute_track_number": TrackField(
        friendly="Absolute Track Number",
        type=int,
        category="Basic",
        tooltip="The track’s overall position in the full album sequence, counting continuously across all discs or sides.",
    ),
    "side": TrackField(
        friendly="Side",
        category="Basic",
        tooltip="The side of the disc or record that contains this track.",
        placeholder="A, B, C, etc.",
        multiple=True,
    ),
    "track_file_path": TrackField(
        friendly="Track File Path",
        short="File Path",
        category="Properties",
        tooltip="The absolute file path to the track.",
        editable=False,
    ),
    "duration": TrackField(
        friendly="Duration",
        short="Length",
        type=float,
        editable=False,
        tooltip="The track run time in seconds.",
        category="Properties",
    ),
    "file_size": TrackField(
        friendly="Track File Size",
        short="Size",
        editable=False,
        tooltip="The size of the file on the disk",
        type=float,
        category="Properties",
    ),
    "file_extension": TrackField(
        category="Properties",
        friendly="File Extension",
        short="Extension",
        tooltip="The type of file.",
        editable=False,
    ),
    "track_name_original": TrackField(
        category="Alias",
        friendly="Original Track Title",
        short="Original Title",
        tooltip="The original title of the track in the language's native script.",
        placeholder="稲妻ブルース",
    ),
    "track_name_transcribed": TrackField(
        category="Alias",
        friendly="Transcribed Track Title",
        short="Transcribed Title",
        tooltip="The track title transcribed to your local script",
        placeholder="Inazuma Burūsu",
    ),
    "track_name_translated": TrackField(
        category="Alias",
        friendly="Translated Track Title",
        short="Translated Title",
        tooltip="The title of the track translated into your language.",
        placeholder="Lightning Blues",
    ),
    "track_name_official": TrackField(
        category="Alias",
        friendly="Official Track Title",
        short="Official Title",
        tooltip="The official credited track title",
        placeholder="INAZUMA BLUES",
    ),
    "track_name_stylized": TrackField(
        category="Alias",
        tooltip="The track title with any special styling applied.",
        short="Stylized Name",
        friendly="Stylized Track Title",
        placeholder="稲妻B L U E S",
    ),
    "recorded_year": TrackField(
        type=int,
        category="Date",
        friendly="Recording Year",
        tooltip="The year the track was recorded.",
        multiple=True,
    ),
    "recorded_month": TrackField(
        type=int,
        category="Date",
        friendly="Recording Month",
        tooltip="The month the track was recorded.",
        max=12,
        multiple=True,
    ),
    "recorded_day": TrackField(
        type=int,
        category="Date",
        friendly="Recording Day",
        tooltip="The day the track was recorded.",
        multiple=True,
    ),
    "remaster_year": TrackField(
        type=int,
        category="Date",
        friendly="Remaster Year",
        tooltip="The year the track was remastered.",
        multiple=True,
    ),
    "composed_year": TrackField(
        type=int,
        category="Classical",
        friendly="Composed Year",
        tooltip="The year the piece was composed.",
        multiple=True,
    ),
    "composed_month": TrackField(
        type=int,
        category="Classical",
        friendly="Composed Month",
        tooltip="The month the piece was composed.",
        multiple=True,
        max=12,
    ),
    "composed_day": TrackField(
        type=int,
        category="Classical",
        friendly="Composed Day",
        tooltip="The day the piece was composed.",
        multiple=True,
    ),
    "first_performed_year": TrackField(
        type=int,
        category="Classical",
        friendly="First Performed Year",
        tooltip="The year the piece was first performed.",
        multiple=True,
    ),
    "is_classical": TrackField(
        type=bool,
        category="Classical",
        friendly="Classical",
        short="Classical",
        tooltip="Indicates whether this release or track belongs to the classical genre, following conventions for classical metadata handling.",
        multiple=True,
    ),
    "work_name": TrackField(
        category="Classical",
        friendly="Work Name",
        short="Work",
        tooltip="The name of the larger work this piece is part of.",
        placeholder="Symphony No. 5",
        multiple=True,
    ),
    "work_type": TrackField(
        category="Classical",
        friendly="Work Type",
        short="Work Type",
        tooltip="The type or genre of the larger work.",
        placeholder="Symphony, Sonata, Concerto, etc.",
        multiple=True,
    ),
    "classical_catalog_prefix": TrackField(
        category="Classical",
        friendly="Classical Catalog Prefix",
        short="Catalog Prefix",
        tooltip="The catalog prefix for the classical work.",
        placeholder="Op., K., BWV, etc.",
        multiple=True,
    ),
    "classical_catalog_number": TrackField(
        type=int,
        category="Classical",
        friendly="Classical Catalog Number",
        short="Catalog Number",
        tooltip="The catalog number for the classical work.",
        placeholder="e.g., 67, 1041, 545, etc.",
        multiple=True,
    ),
    "classical_tempo": TrackField(
        category="Classical",
        friendly="Classical Tempo",
        short="Tempo",
        tooltip="The tempo marking for the piece.",
        placeholder="Allegro, Andante, Presto, etc.",
        multiple=True,
    ),
    "movement_name": TrackField(
        category="Classical",
        friendly="Movement Name",
        short="Movement",
        tooltip="The name of the movement within the larger work.",
        placeholder="Allegro con brio",
        multiple=True,
    ),
    "movement_number": TrackField(
        type=int,
        category="Classical",
        friendly="Movement Number",
        short="Movement No.",
        tooltip="The number of the movement within the larger work.",
        placeholder="e.g., 1, 2, 3, etc.",
        multiple=True,
    ),
    "isrc": TrackField(
        category="Identification",
        friendly="ISRC",
        tooltip="The International Standard Recording Code for the track.",
        placeholder="e.g., US-S1Z-99-00001",
    ),
    "track_copyright": TrackField(
        category="Identification",
        friendly="Track Copyright",
        tooltip="The copyright information for the track.",
        placeholder="e.g., © 2023 Music Library",
    ),
    "MBID": TrackField(
        category="Identification",
        friendly="MusicBrainz ID",
        short="MBID",
        tooltip="The MusicBrainz Identifier for the track.",
        placeholder="e.g., a1b2c3d4-e5f6-7g8h-9i0j-k1l2m3n4o5p6",
    ),
    "track_barcode": TrackField(
        category="Identification",
        friendly="Track Barcode",
        short="Barcode",
        tooltip="The barcode associated with the track.",
        placeholder="e.g., 0123456789123",
    ),
    "track_wikipedia_link": TrackField(
        category="Identification",
        friendly="Track Wikipedia Link",
        short="Wikipedia",
        tooltip="A link to the track's Wikipedia page.",
        placeholder="e.g., https://en.wikipedia.org/wiki/Track_Name",
    ),
    "bpm": TrackField(
        type=int,
        category="Properties",
        friendly="Beats Per Minute (BPM)",
        short="BPM",
        tooltip="The tempo of the track in beats per minute.",
        min=0,
        max=300,
        multiple=True,
    ),
    "track_gain": TrackField(
        type=float,
        category="Properties",
        friendly="Track Gain (dB)",
        short="Gain",
        tooltip="The gain adjustment for the track in decibels.",
        min=-20.0,
        max=20.0,
        multiple=True,
    ),
    "track_peak": TrackField(
        type=float,
        category="Properties",
        friendly="Track Peak",
        short="Peak",
        tooltip="The peak amplitude of the track.",
        min=0.0,
        max=1.0,
        multiple=True,
    ),
    "key": TrackField(
        category="Properties",
        friendly="Musical Key",
        short="Key",
        tooltip="The musical key of the track (e.g., C Major, A Minor).",
        placeholder="e.g., C, A, G",
        length=1,
        multiple=True,
    ),
    "mode": TrackField(
        category="Properties",
        friendly="Musical Mode",
        short="Mode",
        tooltip="The musical mode of the track (e.g., Major, Minor).",
        placeholder="e.g., Major, Minor",
        multiple=True,
    ),
    "key_confidence": TrackField(
        type=float,
        category="Properties",
        friendly="Key Confidence",
        short="Key Conf.",
        tooltip="The confidence level of the detected key.",
        editable=False,
        min=0.0,
        max=1.0,
    ),
    "tempo_confidence": TrackField(
        type=float,
        category="Properties",
        friendly="Tempo Confidence",
        short="Tempo Conf.",
        tooltip="The confidence level of the detected tempo (BPM).",
        editable=False,
        min=0.0,
        max=1.0,
    ),
    "primary_time_signature": TrackField(
        category="Properties",
        friendly="Time Signature",
        short="Time Sig.",
        tooltip="The primary time signature of the track.",
        placeholder="e.g., 4/4, 3/4",
        multiple=True,
    ),
    "user_rating": TrackField(
        type=float,
        category="User",
        friendly="User Rating",
        short="Rating",
        tooltip="The user's rating for the track.",
        min=0.0,
        max=10.0,
        multiple=True,
    ),
    "bit_rate": TrackField(
        type=int,
        category="Properties",
        friendly="Bit Rate (kbps)",
        short="Bit Rate",
        tooltip="The bit rate of the audio file in kilobits per second.",
        editable=False,
    ),
    "sample_rate": TrackField(
        type=int,
        category="Properties",
        friendly="Sample Rate (Hz)",
        short="Sample Rate",
        tooltip="Specifies how many audio samples are captured per second, determining the recording resolution and frequency detail.",
        editable=False,
    ),
    "channels": TrackField(
        type=int,
        category="Properties",
        friendly="Audio Channels",
        short="Channels",
        tooltip="The number of audio channels (e.g., 2 for stereo).",
        editable=False,
    ),
    "bit_depth": TrackField(
        type=int,
        category="Properties",
        friendly="Bit Depth",
        short="Bit Depth",
        tooltip="Indicates the number of bits used to represent each audio sample, affecting dynamic range and audio precision.",
        editable=False,
    ),
    "last_listened_date": TrackField(
        type=datetime,
        category="User",
        friendly="Last Listened Date",
        short="Last Listened",
        tooltip="The date and time when the track was last listened to.",
        editable=False,
    ),
    "is_fixed": TrackField(
        type=bool,
        category="User",
        friendly="Is Fixed",
        short="Fixed",
        tooltip="Indicates whether the user considers track metadata complete.",
        multiple=True,
    ),
    "track_quality": TrackField(
        category="User",
        friendly="Track Quality",
        short="Quality",
        tooltip="The user's assessment of the track's quality.",
        multiple=True,
    ),
    "comment": TrackField(
        category="User",
        friendly="User Comment",
        short="Comment",
        tooltip="User comments or notes about the track.",
        multiple=True,
    ),
    "date_added": TrackField(
        type=datetime,
        category="User",
        friendly="Date Added",
        short="Added",
        tooltip="The date and time when the track was added to the library.",
        editable=False,
    ),
    "play_count": TrackField(
        type=int,
        category="User",
        friendly="Play Count",
        short="Plays",
        tooltip="The number of times the track has been played.",
        editable=False,
    ),
    "lyrics": TrackField(
        category="Lyrics",
        friendly="Lyrics",
        short="Lyrics",
        tooltip="The written words of the track, which can be displayed, edited, or synchronized with the audio.",
        longtext=True,
    ),
    "track_description": TrackField(
        category="Basic",
        friendly="Track Description",
        short="Description",
        tooltip="A description or background information about the track.",
        longtext=True,
    ),
    "is_explicit": TrackField(
        type=bool,
        category="Basic",
        friendly="Explicit",
        short="Explicit",
        tooltip="Indicates whether the track contains explicit content.",
        multiple=True,
    ),
    "is_instrumental": TrackField(
        type=bool,
        category="Basic",
        friendly="Instrumental",
        short="Instrumental",
        tooltip="Indicates whether the track is instrumental.",
        multiple=True,
    ),
    "spectral_centroid": TrackField(
        type=float,
        category="Advanced",
        friendly="Spectral Centroid",
        short="Spec. Centroid",
        tooltip="Represents the “center of mass” of the spectrum, giving a measure of the brightness of a sound. Higher values indicate brighter, more high-frequency content.",
        editable=False,
    ),
    "spectral_rolloff": TrackField(
        type=float,
        category="Advanced",
        friendly="Spectral Rolloff",
        short="Spec. Rolloff",
        tooltip="The frequency below which a specified percentage of the total spectral energy is contained, often used to distinguish harmonic content from noise.",
        editable=False,
    ),
    "dynamic_range": TrackField(
        type=float,
        category="Advanced",
        friendly="Dynamic Range",
        short="Dyn. Range",
        tooltip="Measures the difference between the quietest and loudest parts of the audio, indicating how much variation in volume is present. Higher values generally reflect greater detail and nuance.",
        editable=False,
    ),
    "stereo_width": TrackField(
        type=float,
        category="Advanced",
        friendly="Stereo Width",
        short="Stereo Width",
        tooltip="Describes the perceived spatial separation between the left and right channels, indicating how wide or narrow the stereo image of the recording is.",
        editable=False,
    ),
    "transient_strength": TrackField(
        type=float,
        category="Advanced",
        friendly="Transient Ratio",
        short="Transient Ratio",
        tooltip="Represents the frequency and intensity of sudden changes in amplitude, capturing the sharpness or percussive characteristics of the audio.",
        editable=False,
    ),
    "danceability": TrackField(
        type=float,
        category="Advanced",
        friendly="Danceability",
        short="Danceability",
        tooltip="A measure of how suitable a track is for dancing.",
        min=0.0,
        max=1.0,
        editable=False,
    ),
    "energy": TrackField(
        type=float,
        category="Advanced",
        friendly="Energy",
        short="Energy",
        tooltip="A measure of intensity and activity in the track.",
        min=0.0,
        max=1.0,
        editable=False,
    ),
    "acousticness": TrackField(
        type=float,
        category="Advanced",
        friendly="Acousticness",
        short="Acousticness",
        tooltip="A measure of the acoustic quality of the track.",
        min=0.0,
        max=1.0,
        editable=False,
    ),
    "liveness": TrackField(
        type=float,
        category="Advanced",
        friendly="Liveness",
        short="Liveness",
        tooltip="A measure of the presence of an audience in the recording.",
        min=0.0,
        max=1.0,
        editable=False,
    ),
    "valence": TrackField(
        type=float,
        category="Advanced",
        friendly="Valence",
        short="Valence",
        tooltip="Represents the musical positivity of a track, indicating how happy, cheerful, or pleasant it sounds on a scale from low (sad/negative) to high (happy/positive).",
        min=0.0,
        max=1.0,
        editable=False,
    ),
    "fidelity_score": TrackField(
        type=float,
        category="Advanced",
        friendly="Fidelity Score",
        short="Fidelity",
        tooltip="Quantifies the overall audio fidelity of the track, combining aspects like compression and spectral flatness to indicate how true and detailed the recording is to the original sound.",
        min=0.0,
        max=1.0,
        editable=False,
    ),
    "album_name": TrackField(
        category="Basic",
        friendly="Album Name",
        short="Album",
        tooltip="The name of the album the track belongs to.",
        editable=False,
    ),
    "release_year": TrackField(
        type=int,
        category="Date",
        friendly="Release Year",
        short="Year",
        tooltip="The year the album was released.",
        editable=False,
    ),
    "release_month": TrackField(
        type=int,
        category="Date",
        friendly="Release Month",
        short="Month",
        tooltip="The month the album was released.",
        editable=False,
        max=12,
    ),
    "release_day": TrackField(
        type=int,
        category="Date",
        friendly="Release Day",
        short="Day",
        tooltip="The day the album was released.",
        editable=False,
    ),
    "primary_artist_names": TrackField(
        category="Basic",
        friendly="Primary Artist(s)",
        short="Artist",
        tooltip="The name of the primary artist(s) for the track.",
        editable=False,
    ),
    "disc_number": TrackField(
        type=int,
        category="Basic",
        friendly="Disc Number",
        short="Disc #",
        tooltip="The disc number within a multi-disc album.",
        multiple=True,
    ),
}
